"""
Django settings for form project.

Generated by 'django-admin startproject' using Django 3.1.3.
"""

from pathlib import Path
import os
import socket

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Base URL configuration
BASE_URL = 'https://example.com'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5&41du-&cv-cazt$r@k84h*gz-s!*jk2b)131ek^2-lpou#2y4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False  # Cambiado a False para producción

# Get local IP address
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.connect(("8.8.8.8", 80))
local_ip = s.getsockname()[0]
s.close()

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'index',
    'sslserver',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'form.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'form.wsgi.application'

# CAMBIAR ESTO A DATOS REALES DE TU BASE DE DATOS SEA MYSQL, SQLite PostgreSQL

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sistema',
        'USER': 'root',
        'PASSWORD': '1234',  # Considera usar variables de entorno
        'HOST': 'localhost',
        'PORT': '3306',
    }
}




# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "index.User"

# Internationalization
LANGUAGE_CODE = 'es-cl'  # Cambiado a español de Chile
TIME_ZONE = 'America/Santiago'  # Cambiado a zona horaria de Chile
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# SSL/TLS Configuration
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = [
    'https://exmaple.com',
    'https://www.example.com'
]

# HSTS Settings
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# SSL Certificate Paths PONER TUS DATOS REALES
SSL_CERTIFICATE = os.path.join(BASE_DIR, 'ssl', 'crt')
SSL_PRIVATE_KEY = os.path.join(BASE_DIR, 'ssl', 'key')
SSL_CA_CERTIFICATE = os.path.join(BASE_DIR, 'ssl', 'crt')
SSL_CHAIN_CERTIFICATE = os.path.join(BASE_DIR, 'ssl', 'crt')

# Para Nginx/Apache (referencia)
SSL_CERTIFICATE_CHAIN = f"{SSL_CERTIFICATE} {SSL_CHAIN_CERTIFICATE}"

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'